# Permalinks
#
permalink:           pretty

# Setup
title:               Large Canadian Roadside Attractions
tagline:             'Bigger is better!'
url:                 http://roadsideattractions.ca
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Michael A. van Bodegom
  url:               http://roadsideattractions.ca
  email:             mike@roadsideattractions.ca

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
paginate_path: "page:num"
