---
title: Large Canadian Roadside Attractions
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: pretty
tagline: Bigger is better!
url: http://blog.roadsideattractions.ca
baseurl: ''
paginate: 5
author:
  name: Michael A. van Bodegom
  url: http://blog.roadsideattractions.ca
  email: mike@roadsideattractions.ca
version: 1.0.0
gems:
- jekyll-paginate
paginate_path: page:num
